### PR TITLE
Update ST_Anything_Multiples_ESP32WiFi.ino

### PR DESCRIPTION
**Pull request by vseven**
Updated the example sketch for the RGB LED/Strip capability.  Removed a water, illuminance, and a motion sensor to fit in the three pins needed by the RGB LED or strip.  Believe I reordered all the numbering correctly.

Once this is merged in and I get more people to test it I'll try to update the 8266 example sketch.  Not sure if any others really need to be done...think 8266 is the most used and the 32 will be as time goes on.

### CODE REVIEW

**Comment by ogiewon** [comment]
How about you add an entirely new example sketch (e.g. ST_Anything_RGBLED_ESP32WiFi.ino) to demonstrate the use of the RGB LED capability?  I think most people who want to drive an LED strip will probably not be using too many any other devices at the same time.  I'd like to keep the existing "Mulitples" sketches as-is for now to avoid confusion for users.

I have a string of NeoPixel LEDs that I will probably look at adding support for in the near future, now that you've blazed the trail for RGB lighting.  Thank you very much for your additions to ST_Anything!

**Comment by vseven** [comment]
I can add a new example but the reason I tried to fit it in was the devices I removed were all ones that had multiples already so nothing was really removed example wise.  I.e. there was two motion sensors, two water, and two illumanance so I removed one of each to find the room.  I left the two alarm devices since there were two distinct examples.  But if you think there should be a new one like the 8266 alarm panel in addition to the 8266 multiples I can do that.  Although if I do I'd try to create a RGBW device first and show both examples.

With the above said I know I will be using multiples on my ESP32.  When I soldered it I left room for extra analogs along with SDA/SDL, etc in case I wanted to use them.  I could easily add a RGB LED to the panel since its right by the garage door entrance to show status of the system.  Like Red for armed, green for not armed but all contacts closed, blue for something open, etc.  But I understand wanting a seperate one.  Just giving my reasoning.

As for the NeoPixels I looked at doing them first but the issue was I couldn't think of a situation where you could individually address pixels which would be the main advantage of them.  I.e. from SmartThings you'd be turning them all on and off and to a certain color as there is no way to have a device handler do all the various combinations or address individual pixels.   It would be a all or nothing kinda code.   And at that point, since it would eliminate the advantages of individually addressable pixels, I went with the cheaper option of RGB strips....just standard "analog" ones.  With that said adding them in should be easy using the EX_RGB_Switch framework and the Child RGB Device handler.  Making them actually addressable and enabling advanced functions from SmartThings however would be difficult (just because of the DTH side).  I have debated buying some just to try programming them but in the end for me it would be a waste.

You wanna say something on the ST_Anything thread about these additions or do you mind if I do?  And let me know about the example.

**Comment by ogiewon** [comment]
Let's go with a new set of example sketches for the ESP32, ESP8266, etc...  I understand your reasoning, but I think it will help users to have have example sketches that are somewhat more purpose-build, like I did for the Alarm Panel.

As for the NeoPixels, I agree that it is not obvious as to how to utilize their full capability.  However, they do operate in a digital manner, requiring fewer pins to operate, but you also have to know how many pixels are in the strip...  Again, not obvious, but since all I have is NeoPixels currently, I think it'll be fun to give them a try.

**Comment by vseven** [comment]
Example sketches are done and PR's entered.  Just RGB for now, once someone tests the RGB on a 8266 and it works like mine on a ESP32 I can duplicate the DTH for RGBW and update the examples.  RGBW on a 8266 would be kinda tight since it would take up 4 pins real quick.  ESP32 could do a bunch though.  

I was reading up on the NeoPixels a lot.  They only need a single digital pin and from their example library it doesn't seem too hard to control them (just like the TCS light sensor I did...its all in their library).  It's just no real way of doing it from SmartThings.  Like on a strip of 150 pixels change 1 - 60 to this color, 61 - 90 to this color, then 91 - 150 to this color...no way to design a DTH for that.  All the same color plus on/off should be easy though.  Constructor is easier too since there are less pins to deal with, just a single pin for control and the number of pixels being controlled.  

But since its only the single pin you could fit a lot more on controller. For me its not worth the extra costs since I'll be using a eSP32 but if you have 8266's already and outputs are scarce it could make sense.  And like I said you could write some custom routines to send functions back tot he device.

**Comment by ogiewon** [comment]
Sounds good. I have merged your two new PRs. I guess we should close this one, correct?

**Comment by vseven** [comment]
Sure.  I would assume for the NeoPixels you would use the same handler I made and just modify the EX_RGB_Dim code so if you have any questions (probably not) with anything let me know.  I'm just sending on/off and setColor as a HEX string (#RRGGBB).  The DTH takes care of dimming also and adjusts the hex so if you are sending pure red (#FF0000) and you set the dimmer to 50% it does the calculation and resends the hex (#880000).  If your NeoPixels have a white channel (RGBW) let me know, I can make a DTH pretty easily I think.  It would just be a extra slider just for white like the Fibaro does and I'd send down the hex as #RRGGBBWW and let the device code interpret it.

**Pull request closed without merging**
