### PR TITLE
Adding OTA support

### PR DESCRIPTION
**Pull request by zybeon**
Not the cleanest way to add OTA support but the fastest. The cleanest way would be to modify the library files to keep this code out of the main .ino file and for faster portability to new sketches.

### CODE REVIEW

**Comment by ogiewon** [comment]
Help me understand the difference between the two OTA update features in your PR, please.  I think I understand the difference, but want to make sure.  

Another ST user added Arduino OTA updates simply by adding a few lines of code to his sketch.  See his work at the following link for a potentially slightly simpler implementation of the Arduino OTA updates (the more I look at both yours and his, the more similar I see they are... :) ) 

https://community.smartthings.com/t/release-st-anything-v2-8-arduino-esp8266-esp32-to-st-via-thingshield-ethernet-or-wifi/77707/900

I am pretty certain that I could add this capability directly to the SmartThingsESP8266WiFi library instead of having to modify every sketch.  

Give me a few days to mess around with it.  If you don't here anything from me within a week, please feel free to add a comment here to make sure I haven't forgotten it!  ;)

**Comment by zybeon** [comment]
The ArdOTA adds an update feature through the arduino IDE. The WebOTA adds a http server where you can upload the compiled ino script to flash it.

http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html

**Comment by ogiewon** [comment]
@zybeon I have decided to incorporate the Arduino OTA update capability directly into the "SmartThingsESP8266WiFi" library.  This prevents users from having to modify their sketches.  Thank you for your Pull Request, as it helped to inspire me to finally add this much-requested feature.  

Note:  For now, I chose not to implement the WebOTA capability.  Baby steps...  ;)

**Comment by scottchiefbaker** [comment]
@zybeon I just released [ESP-WebOTA](https://github.com/scottchiefbaker/ESP-WebOTA) for ESP32 devices. I'd like to expand it to include ESP8266 support as well.

Would you be interested in working together on this project? Looks like you know more about the ESP8266 internals than I do.

**Pull request closed without merging**
