### PR TITLE
Fixed InterruptSensor and ContactSensor

### PR DESCRIPTION
**Pull request by gculik**
Fixed a bug in InterruptSensor which caused it to ignore the pull-up flag

Reversed polarities in the ContactSensor so that runInterrupt is the
contact opening, and runInterruptEnded is the contact closing (since
most all contact sensors are Normally Closed)

Added new implementations of EX_Tone and EX_Chime classes.

### CODE REVIEW

**Comment by ogiewon** [comment]
gculik,

My son and I have reviewed these two changes and do not see where either one of them is required.

Specifically:

Issue: Fixed a bug in InterruptSensor which caused it to ignore the pull-up flag

Response:  The pullup up resistor functionality has been working perfectly for over 2 years now with no issues ever noticed here locally, nor ever reported by many users of the library.  Are you using an Arduino UNO R3 or MEGA 2560?  Curious what Arduino platform you've seen the issue with?  How can the issue be reproduced?  Your code simply moves the setting of the pullup resistor mode to slightly later in the code initialization, but executes the exact same code.  I'd be happy to correct any issue if I can figure out how to reproduce it.


Issue: Reversed polarities in the ContactSensor so that runInterrupt is the contact opening, and runInterruptEnded is the contact closing (since most all contact sensors are Normally Closed)

Response:  If you look at the arguments of the constructor for a IS_Contact, you will clearly see that we provided an option for the user to choose whether an Arduino HIGH or LOW state is indicative of a CLOSE or OPEN. By setting the "iState" argument in the constructor as either HIGH or LOW, you can reverse the logic as you see fit for your digital input sensor.  Therefore, there is no reason to change the code. 

Taken directly from the header comment section of IS_Contact.cpp:

//			  st::IS_Contact() constructor requires the following arguments
//				- String &name - REQUIRED - the name of the object - must match the Groovy ST_Anything DeviceType tile name
//				- byte pin - REQUIRED - the Arduino Pin to be used as a digital input
**//				- bool iState - REQUIRED - LOW or HIGH - determines which value indicates the interrupt is true**
//				- bool internalPullup - OPTIONAL - true == INTERNAL_PULLUP
//				- long numReqCounts - OPTIONAL - number of counts before changing state of input (prevent false alarms)
/ 

Let me know if you agree with both of these assessments and I will close this Pull Request without merging these changes.  The second change would break things for a lot of exiting users, requiring changes to everyone's sketches to fix the logic.

Thanks for your feedback!
Dan

**Comment by gculik** [comment]
1) The issue was really with the derived implementation of **EX_Motion** which does a **digitalWrite(pin, LOW)**  while the PIR is calibrating, and then calls **EX_Interrupt::init**, which in the old code did nothing but call **checkIfTriggered**, which basically caused the pullup flag to be ignored.  By fixing the **EX_InterruptSensor**, **EX_Motion** no longer ignores the pullup flag, and also does not break any backward compatibility.

2) I know that all the sensors have a polarity flag on them, and therefore I can pick which polarity I want.  However the implementation is inconsistent with for example the **EX_Motion** implementation.  I will give an example.  I have both Contact and Motion sensors, where I use the pull up flag=true, and in both cases the normal state (the closed state or inactive state), is the circuit is normally closed (connected to ground) or LOW (0V).  When the contact is opened or there is a motion the circuit opens and the state is HIGH (5V).

Now with your current implementation I would have to have the following static declarations
`  static st::IS_Contact frontEntryDoorSensor(F("frontEntryDoor"), PIN_FRONT_ENTRY_DOOR, LOW, true, 500);
  static st::IS_Motion livingRoomMotionSensor(F("livingRoomMotion"), PIN_LIVING_ROOM_MOTION, HIGH, true);
`
which seems completely counter intuitive considering that the underlying circuitry for both sensors is the same.  By correcting the polarities of the EX_Contact I now have the following declaration

`  static st::IS_Contact frontEntryDoorSensor(F("frontEntryDoor"), PIN_FRONT_ENTRY_DOOR, HIGH, true, 500);
  static st::IS_Motion livingRoomMotionSensor(F("livingRoomMotion"), PIN_LIVING_ROOM_MOTION, HIGH, true);`

which mirrors the associated circuits.  While I understand that users upgrading to this new code would have to switch polarities in their existing sketches, this would obviously be documented, and would make the code more consistent.

**Comment by DanielOgorchock** [comment]
Jiri,

Thanks for the clarifications. I now understand what you're talking about with the ignored pullup state ( @ogiewon the motion sensor's digital write causes us to lose the initial configuration done in the parent class). Thanks for the fix.

As for the second point:
I do see value in the added consistency you describe, but I also am not sure if it is worth breaking backwards compatibility to achieve. I'll leave that decision up to @ogiewon, as I think he wrote the motion class. 

The tone and chime stuff looks cool. Thanks for the additions to the library.

**Comment by DanielOgorchock** [comment]
Actually, I think this may require another refactor. Moving the pin initialization to InterruptSensor's init would require that every single inherited class call the parent's init function. I believe this is currently the case, but it could prove problematic in the future. Rather than add this risk, perhaps it would be better to put back the old pin initialization code, and have IS_Motion itself call setInterruptPin() in its init function right before it calls its parent's init function.

**Comment by gculik** [comment]
It makes more sense to me that the ::init method does the actual hardware initialization whether that is setting pin modes or whatever else, rather than having a specialized method for each class.  Considering that all the existing code calls the parent class ::init I don't see how this would be an issue in the future.

**Comment by gculik** [comment]
I would like to add one more argument in favor of my **EX_Contact** implementation.  I would argue that both as an abstract notion of a contact sensor, and as a real contact sensor in any installed security system, that the steady state or normal state of a contact sensor is the **closed** state, and that the interrupted state is the **open** state.  This is true regardless of the external circuit implementation, whether the contact sensor is connected to an input pin with the internal pull-up to ground, or to an input pin through an external pull-down to 5V.  The current implementation is the exact opposite.

**Comment by ogiewon** [comment]
OK, trying to catch back up here...  

On the topic of whether or not a Contact Sensor is normally open or closed, I believe we are going to have to agree to disagree.  I am not willing to break backwards compatibility for existing users.

As for the broken Motion Sensor pullup resistor logic, I agree completely that this is a bug depending on the type of motion sensor you use.  For the PIR sensor I use, I followed other code examples for the Arduino.  I have had another user, who was trying to reuse an old security system motion sensor, report the exact same issue that you've reported.  I resolved the issue once already for that user, but did not update github for fear of breaking backwards compatibility.  I will dust off that code and update Github to make sure the pullup feature works correctly.

**Comment by gculik** [comment]
Hmmm, I would like to know what exactly do you disagree with in my arguments.  Saying that you do not want to break backward compatibility (which amounts to users switching a few lines of code, should they even update to the the new code), is pretty obtuse, in light of the fact, that one can argue that the current implementation is buggy since it does not represent correctly the underlying circuit.  It is certainly a source of confusion for anyone using the code, as it was for me.

I will not bother you in the future since you do not seem to be interested in my help.

**Comment by DanielOgorchock** [comment]
Jiri,

We definitely welcome help with the library and don't mean to imply otherwise.

With regard to the pullup bug, I really think it'd be better not to move the pin initialization to the parent's init function. Derived classes of InterruptSensor should not be required to call their parent's init to set the interrupt pin. The parent's init could one day include a call other than getInterruptState() that a writer of a derived class wouldn't desire. If the pin initialization is moved to InterruptSensor's init there would be no way for a derived class to initialize the pin without having all the InterruptSensor init code run. Putting back the setInterruptPin() call in InterruptSensor's constructor and calling setInteruptPin() in EX_Motion's init is a solution that doesn't make derived classes less versatile. I'd prefer not to restrict authors of derived classes more than is necessary.

We've decided that changing the default polarity of EX_Motion for the sake of consistency isn't worth the risk of someone updating the library without reading about the change and having broken functionality. While I agree that it's a trivial thing to change, it just doesn't seem worth the potential of people's motion sensors randomly stopping working. Maybe a change like this could be revisited if the library undergoes some sort of future overhaul with more sweeping changes.

If you'd like to make these changes and reopen your pull request, we'd gladly accept it. If not, do you mind if I fork your fork and make the changes myself before merging it into the library? I'd definitely like to add your Tone and Chime work to the library.

**Comment by gculik** [comment]
I never mentioned anything about changing **IS_Motion**, which as is, correctly represents the associated circuit.  It was always about correcting the flipped polarity of the **IS_Contact**, which does not represent the associated circuit.

**Comment by DanielOgorchock** [comment]
That was a typo on my part. I meant to refer to IS_Contact.

**Comment by gculik** [comment]
As for the **InterruptSensor** changes, I don't see a difference between having to call base class **::init** and the base class **::setInterruptPin** other than the fact that currently the **::init** also sets the current state by call **checkIfTriggered**.  It seems to me that every single derived class would want to run that code, although now that I think about it, I would even consider taking the **checkIfTriggered** out of the **::init** method all together.  Bottom line is that simpler and cleaner is better, and you already have defined a nice clean interface with the **::init** method.

**Comment by mwright42** [comment]
Geez. Come on guys. Harness the energy. We are all waiting. New energy is what we need.

**Pull request closed without merging**
